// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

console.log("this is reason");


console.log('here is some javascript for you');

;

/*  Not a pure module */
